// <auto-generated />
using System;
using GoEASy.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoEASy.Migrations
{
    [DbContext(typeof(GoEasyContext))]
    [Migration("20250728170330_LogAndStatistics")]
    partial class LogAndStatistics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoEASy.Models.AccessLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LogID")
                        .HasName("PK__AccessLo__5E5499A85C951DF8");

                    b.HasIndex("UserID");

                    b.ToTable("AccessLog", (string)null);
                });

            modelBuilder.Entity("GoEASy.Models.Action", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionId"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActionSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("ActionId")
                        .HasName("PK__Actions__FFE3F4D9CB247AFF");

                    b.HasIndex(new[] { "ActionSlug" }, "UQ__Actions__3148953D6EAEC540")
                        .IsUnique();

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("GoEASy.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RuleId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AdminID")
                        .HasName("PK__Admins__719FE4E80D073614");

                    b.HasIndex("RuleId");

                    b.HasIndex(new[] { "Username" }, "UQ__Admins__536C85E4370D36E6")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Admins__A9D10534F3ACDEC4")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("GoEASy.Models.Blog", b =>
                {
                    b.Property<int>("BlogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogID"));

                    b.Property<int?>("AuthorAdminID")
                        .HasColumnType("int");

                    b.Property<int?>("AuthorUserID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<byte?>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("BlogID")
                        .HasName("PK__Blogs__54379E50DF1D11DB");

                    b.HasIndex("AuthorAdminID");

                    b.HasIndex("AuthorUserID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("GoEASy.Models.BlogComment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentID"));

                    b.Property<int>("BlogID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CommentID")
                        .HasName("PK__BlogComm__C3B4DFAAAA8338B9");

                    b.HasIndex("BlogID");

                    b.HasIndex("UserID");

                    b.ToTable("BlogComments");
                });

            modelBuilder.Entity("GoEASy.Models.BlogDetail", b =>
                {
                    b.Property<int>("BlogDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogDetailID"));

                    b.Property<int>("BlogID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Introduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuoteAuthor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Section1Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section1Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Section2Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section2Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("BlogDetailID")
                        .HasName("PK__BlogDeta__2383E81EBB0A289E");

                    b.HasIndex(new[] { "BlogID" }, "UQ__BlogDeta__54379E519D2CECE0")
                        .IsUnique();

                    b.ToTable("BlogDetails");
                });

            modelBuilder.Entity("GoEASy.Models.BlogImage", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<int>("BlogID")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsMain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("ImageID")
                        .HasName("PK__BlogImag__7516F4EC50ABB3E6");

                    b.HasIndex("BlogID");

                    b.ToTable("BlogImages");
                });

            modelBuilder.Entity("GoEASy.Models.BlogTag", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagID"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("TagID")
                        .HasName("PK__BlogTags__657CFA4CD3671040");

                    b.HasIndex(new[] { "Name" }, "UQ__BlogTags__737584F6C7DCC467")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("BlogTags");
                });

            modelBuilder.Entity("GoEASy.Models.BlogTagMapping", b =>
                {
                    b.Property<int>("BlogID")
                        .HasColumnType("int");

                    b.Property<int>("TagID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("BlogID", "TagID")
                        .HasName("PK__BlogTagM__826051F48E5A3A93");

                    b.HasIndex("TagID");

                    b.ToTable("BlogTagMapping", (string)null);
                });

            modelBuilder.Entity("GoEASy.Models.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<int>("AdultGuests")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BookingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("ChildGuests")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<decimal?>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0.00m);

                    b.Property<int?>("DiscountID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("TotalPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0.00m);

                    b.Property<int?>("TourID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("UsedVIPPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("BookingID")
                        .HasName("PK__Bookings__73951ACD7995049D");

                    b.HasIndex("DiscountID");

                    b.HasIndex("TourID");

                    b.HasIndex("UserID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("GoEASy.Models.Companion", b =>
                {
                    b.Property<int>("CompanionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanionID"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NationalID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CompanionID")
                        .HasName("PK__Companio__8B53BE8BF2A6B57E");

                    b.HasIndex("UserID");

                    b.ToTable("Companions");
                });

            modelBuilder.Entity("GoEASy.Models.Destination", b =>
                {
                    b.Property<int>("DestinationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinationID"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("DestinationID")
                        .HasName("PK__Destinat__DB5FE4AC0F8388C0");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("GoEASy.Models.DestinationImage", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<string>("Caption")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("DestinationID")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsCover")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("ImageID")
                        .HasName("PK__Destinat__7516F4ECAC84A0A5");

                    b.HasIndex("DestinationID");

                    b.ToTable("DestinationImages");
                });

            modelBuilder.Entity("GoEASy.Models.Discount", b =>
                {
                    b.Property<int>("DiscountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscountID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MaxAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("MinTotalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("Percentage")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("DiscountID")
                        .HasName("PK__Discount__E43F6DF60F0748A1");

                    b.HasIndex(new[] { "Code" }, "UQ__Discount__A25C5AA77F6F5670")
                        .IsUnique();

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("GoEASy.Models.Favorite", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("TourID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("UserID", "TourID")
                        .HasName("PK__Favorite__018C020DB0FD2F72");

                    b.HasIndex("TourID");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("GoEASy.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("RelatedId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E12C3DD730E");

                    b.HasIndex(new[] { "UserId" }, "IX_Notifications_UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GoEASy.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("BookingID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("PaymentID")
                        .HasName("PK__Payments__9B556A588D559114");

                    b.HasIndex("BookingID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("GoEASy.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("SentimentScore")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TourID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReviewID")
                        .HasName("PK__Reviews__74BC79AE1781A59E");

                    b.HasIndex("TourID");

                    b.HasIndex("UserID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("GoEASy.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID")
                        .HasName("PK__Roles__8AFACE3AC60AA4DD");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B6160E55A842F")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GoEASy.Models.Rule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool?>("IsOpen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ListRuleSlug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RuleId")
                        .HasName("PK__Rules__110458E23D463170");

                    b.HasIndex(new[] { "Slug" }, "UQ__Rules__BC7B5FB60152F65E")
                        .IsUnique();

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("GoEASy.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleID"));

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TourID")
                        .HasColumnType("int");

                    b.HasKey("ScheduleID")
                        .HasName("PK__Schedule__9C8A5B693C60215D");

                    b.HasIndex("TourID");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("GoEASy.Models.SemanticQuery", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TopK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.HasKey("ID")
                        .HasName("PK__Semantic__3214EC276AF0C059");

                    b.ToTable("SemanticQueries");
                });

            modelBuilder.Entity("GoEASy.Models.Tour", b =>
                {
                    b.Property<int>("TourID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TourID"));

                    b.Property<decimal>("AdultPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<decimal>("ChildPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DestinationID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxSeats")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("TourName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TourID")
                        .HasName("PK__Tours__604CEA109ED306E5");

                    b.HasIndex("CategoryID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DestinationID");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("GoEASy.Models.TourCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("CategoryID")
                        .HasName("PK__TourCate__19093A2B9A58ECFD");

                    b.HasIndex(new[] { "CategoryName" }, "UQ__TourCate__8517B2E005F3C24C")
                        .IsUnique();

                    b.ToTable("TourCategories");
                });

            modelBuilder.Entity("GoEASy.Models.TourDetail", b =>
                {
                    b.Property<int>("TourDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TourDetailID"));

                    b.Property<string>("Activities")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Excluded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Included")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TourID")
                        .HasColumnType("int");

                    b.HasKey("TourDetailID")
                        .HasName("PK__TourDeta__5055BCFC2BC8AA78");

                    b.HasIndex(new[] { "TourID" }, "UQ__TourDeta__604CEA11C9A3D5D6")
                        .IsUnique();

                    b.ToTable("TourDetails");
                });

            modelBuilder.Entity("GoEASy.Models.TourDto", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID")
                        .HasName("PK__TourDtos__3214EC27A24F8788");

                    b.ToTable("TourDtos");
                });

            modelBuilder.Entity("GoEASy.Models.TourFAQ", b =>
                {
                    b.Property<int>("FAQID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FAQID"));

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TourID")
                        .HasColumnType("int");

                    b.HasKey("FAQID")
                        .HasName("PK__TourFAQs__4B89D1E29DD13A3D");

                    b.HasIndex("TourID");

                    b.ToTable("TourFAQs");
                });

            modelBuilder.Entity("GoEASy.Models.TourImage", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<string>("Caption")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsCover")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("TourID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("ImageID")
                        .HasName("PK__TourImag__7516F4EC6D54EB2C");

                    b.HasIndex("TourID");

                    b.ToTable("TourImages");
                });

            modelBuilder.Entity("GoEASy.Models.TourItinerary", b =>
                {
                    b.Property<int>("ItineraryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItineraryID"));

                    b.Property<string>("Accommodation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Meals")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("TourID")
                        .HasColumnType("int");

                    b.HasKey("ItineraryID")
                        .HasName("PK__TourItin__361216A643F3D5DB");

                    b.HasIndex("TourID");

                    b.ToTable("TourItineraries");
                });

            modelBuilder.Entity("GoEASy.Models.TourPolicy", b =>
                {
                    b.Property<int>("PolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyID"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PolicyDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PolicyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PolicyValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TourID")
                        .HasColumnType("int");

                    b.HasKey("PolicyID")
                        .HasName("PK__TourPoli__PolicyID");

                    b.HasIndex("TourID");

                    b.ToTable("TourPolicies", (string)null);
                });

            modelBuilder.Entity("GoEASy.Models.TourViewLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TourID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ViewTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ID")
                        .HasName("PK__TourView__3214EC27BB638F86");

                    b.ToTable("TourViewLogs");
                });

            modelBuilder.Entity("GoEASy.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsVIP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("Sex")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("VIPPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("UserID")
                        .HasName("PK__Users__1788CCACA986BA0B");

                    b.HasIndex("RoleID");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E4240F0354")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105348693C07F")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GoEASy.Models.VIPPointHistory", b =>
                {
                    b.Property<int>("HistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryID"));

                    b.Property<int?>("ChangeAmount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("HistoryID")
                        .HasName("PK__VIPPoint__4D7B4ADD9AEB3685");

                    b.HasIndex("UserID");

                    b.ToTable("VIPPointHistory", (string)null);
                });

            modelBuilder.Entity("GoEASy.Models.AccessLog", b =>
                {
                    b.HasOne("GoEASy.Models.User", "User")
                        .WithMany("AccessLogs")
                        .HasForeignKey("UserID")
                        .HasConstraintName("FK__AccessLog__UserI__10566F31");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoEASy.Models.Admin", b =>
                {
                    b.HasOne("GoEASy.Models.Rule", "Rule")
                        .WithMany("Admins")
                        .HasForeignKey("RuleId")
                        .HasConstraintName("FK_Admins_Rules");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("GoEASy.Models.Blog", b =>
                {
                    b.HasOne("GoEASy.Models.Admin", "AuthorAdmin")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorAdminID")
                        .HasConstraintName("FK__Blogs__AuthorAdm__0B5CAFEA");

                    b.HasOne("GoEASy.Models.User", "AuthorUser")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorUserID")
                        .HasConstraintName("FK__Blogs__AuthorUse__0A688BB1");

                    b.HasOne("GoEASy.Models.TourCategory", "Category")
                        .WithMany("Blogs")
                        .HasForeignKey("CategoryID")
                        .IsRequired()
                        .HasConstraintName("FK__Blogs__CategoryI__0C50D423");

                    b.Navigation("AuthorAdmin");

                    b.Navigation("AuthorUser");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GoEASy.Models.BlogComment", b =>
                {
                    b.HasOne("GoEASy.Models.Blog", "Blog")
                        .WithMany("BlogComments")
                        .HasForeignKey("BlogID")
                        .IsRequired()
                        .HasConstraintName("FK__BlogComme__BlogI__15DA3E5D");

                    b.HasOne("GoEASy.Models.User", "User")
                        .WithMany("BlogComments")
                        .HasForeignKey("UserID")
                        .HasConstraintName("FK__BlogComme__UserI__16CE6296");

                    b.Navigation("Blog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoEASy.Models.BlogDetail", b =>
                {
                    b.HasOne("GoEASy.Models.Blog", "Blog")
                        .WithOne("BlogDetail")
                        .HasForeignKey("GoEASy.Models.BlogDetail", "BlogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__BlogDetai__BlogI__1209AD79");

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("GoEASy.Models.BlogImage", b =>
                {
                    b.HasOne("GoEASy.Models.Blog", "Blog")
                        .WithMany("BlogImages")
                        .HasForeignKey("BlogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__BlogImage__BlogI__1B9317B3");

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("GoEASy.Models.BlogTagMapping", b =>
                {
                    b.HasOne("GoEASy.Models.Blog", "Blog")
                        .WithMany("BlogTagMappings")
                        .HasForeignKey("BlogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__BlogTagMa__BlogI__2334397B");

                    b.HasOne("GoEASy.Models.BlogTag", "Tag")
                        .WithMany("BlogTagMappings")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__BlogTagMa__TagID__24285DB4");

                    b.Navigation("Blog");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("GoEASy.Models.Booking", b =>
                {
                    b.HasOne("GoEASy.Models.Discount", "Discount")
                        .WithMany("Bookings")
                        .HasForeignKey("DiscountID")
                        .HasConstraintName("FK__Bookings__Discou__76969D2E");

                    b.HasOne("GoEASy.Models.Tour", "Tour")
                        .WithMany("Bookings")
                        .HasForeignKey("TourID")
                        .HasConstraintName("FK__Bookings__TourID__75A278F5");

                    b.HasOne("GoEASy.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserID")
                        .HasConstraintName("FK__Bookings__UserID__74AE54BC");

                    b.Navigation("Discount");

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoEASy.Models.Companion", b =>
                {
                    b.HasOne("GoEASy.Models.User", "User")
                        .WithMany("Companions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Companion__UserI__1BC821DD");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoEASy.Models.DestinationImage", b =>
                {
                    b.HasOne("GoEASy.Models.Destination", "Destination")
                        .WithMany("DestinationImages")
                        .HasForeignKey("DestinationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Destinati__Desti__52593CB8");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("GoEASy.Models.Favorite", b =>
                {
                    b.HasOne("GoEASy.Models.Tour", "Tour")
                        .WithMany("Favorites")
                        .HasForeignKey("TourID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Favorites__TourI__08B54D69");

                    b.HasOne("GoEASy.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Favorites__UserI__07C12930");

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoEASy.Models.Payment", b =>
                {
                    b.HasOne("GoEASy.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingID")
                        .HasConstraintName("FK__Payments__Bookin__7B5B524B");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("GoEASy.Models.Review", b =>
                {
                    b.HasOne("GoEASy.Models.Tour", "Tour")
                        .WithMany("Reviews")
                        .HasForeignKey("TourID")
                        .HasConstraintName("FK__Reviews__TourID__01142BA1");

                    b.HasOne("GoEASy.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserID")
                        .HasConstraintName("FK__Reviews__UserID__00200768");

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoEASy.Models.Schedule", b =>
                {
                    b.HasOne("GoEASy.Models.Tour", "Tour")
                        .WithMany("Schedules")
                        .HasForeignKey("TourID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Schedules__TourI__6477ECF3");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("GoEASy.Models.Tour", b =>
                {
                    b.HasOne("GoEASy.Models.TourCategory", "Category")
                        .WithMany("Tours")
                        .HasForeignKey("CategoryID")
                        .HasConstraintName("FK__Tours__CategoryI__5CD6CB2B");

                    b.HasOne("GoEASy.Models.User", "CreatedByNavigation")
                        .WithMany("Tours")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Tours__CreatedBy__5AEE82B9");

                    b.HasOne("GoEASy.Models.Destination", "Destination")
                        .WithMany("Tours")
                        .HasForeignKey("DestinationID")
                        .HasConstraintName("FK__Tours__Destinati__5BE2A6F2");

                    b.Navigation("Category");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("GoEASy.Models.TourDetail", b =>
                {
                    b.HasOne("GoEASy.Models.Tour", "Tour")
                        .WithOne("TourDetail")
                        .HasForeignKey("GoEASy.Models.TourDetail", "TourID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TourDetai__TourI__5BAD9CC8");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("GoEASy.Models.TourFAQ", b =>
                {
                    b.HasOne("GoEASy.Models.Tour", "Tour")
                        .WithMany("TourFAQs")
                        .HasForeignKey("TourID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TourFAQs__TourID__634EBE90");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("GoEASy.Models.TourImage", b =>
                {
                    b.HasOne("GoEASy.Models.Tour", "Tour")
                        .WithMany("TourImages")
                        .HasForeignKey("TourID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__TourImage__TourI__619B8048");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("GoEASy.Models.TourItinerary", b =>
                {
                    b.HasOne("GoEASy.Models.Tour", "Tour")
                        .WithMany("TourItineraries")
                        .HasForeignKey("TourID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__TourItine__TourI__5F7E2DAC");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("GoEASy.Models.TourPolicy", b =>
                {
                    b.HasOne("GoEASy.Models.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TourPolicies__TourID");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("GoEASy.Models.User", b =>
                {
                    b.HasOne("GoEASy.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .HasConstraintName("FK__Users__RoleID__412EB0B6");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GoEASy.Models.VIPPointHistory", b =>
                {
                    b.HasOne("GoEASy.Models.User", "User")
                        .WithMany("VIPPointHistories")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__VIPPointH__UserI__0C85DE4D");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoEASy.Models.Admin", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("GoEASy.Models.Blog", b =>
                {
                    b.Navigation("BlogComments");

                    b.Navigation("BlogDetail");

                    b.Navigation("BlogImages");

                    b.Navigation("BlogTagMappings");
                });

            modelBuilder.Entity("GoEASy.Models.BlogTag", b =>
                {
                    b.Navigation("BlogTagMappings");
                });

            modelBuilder.Entity("GoEASy.Models.Booking", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("GoEASy.Models.Destination", b =>
                {
                    b.Navigation("DestinationImages");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("GoEASy.Models.Discount", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("GoEASy.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("GoEASy.Models.Rule", b =>
                {
                    b.Navigation("Admins");
                });

            modelBuilder.Entity("GoEASy.Models.Tour", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Favorites");

                    b.Navigation("Reviews");

                    b.Navigation("Schedules");

                    b.Navigation("TourDetail");

                    b.Navigation("TourFAQs");

                    b.Navigation("TourImages");

                    b.Navigation("TourItineraries");
                });

            modelBuilder.Entity("GoEASy.Models.TourCategory", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("GoEASy.Models.User", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("BlogComments");

                    b.Navigation("Blogs");

                    b.Navigation("Bookings");

                    b.Navigation("Companions");

                    b.Navigation("Favorites");

                    b.Navigation("Reviews");

                    b.Navigation("Tours");

                    b.Navigation("VIPPointHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
